apiVersion: skaffold/v2beta24
kind: Config
build:
  local:
    concurrency: 3
    useBuildkit: true
  artifacts:
    - image: kubesail/sync
      context: .
      sync:
        manual:
          - src: "**/*"
            dest: .
deploy:
  kustomize:
    paths:
      - k8s
  statusCheckDeadlineSeconds: 180
portForward:
  - resourceType: Service
    resourceName: kubesail-sync
    port: 9099
    address: 0.0.0.0
    localPort: 9099
